version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=taskdb
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "user", "-ppassword" ]
      interval: 10s
      timeout: 5s
      retries: 5

  pubsub:
    image: gcr.io/google.com/cloudsdktool/cloud-sdk:latest
    entrypoint: gcloud beta emulators pubsub start --host-port=0.0.0.0:8085 --project=task-project
    ports:
      - "8085:8085"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "8085" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql-data:
